package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Rubén Darío Martínez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaButton();
    }
    
     public void transparenciaButton(){
        PlanearViaje.setOpaque(false);
        PlanearViaje.setContentAreaFilled(false);
        PlanearViaje.setBorderPainted(false);
        
        BuscarRutas.setOpaque(false);
        BuscarRutas.setContentAreaFilled(false);
        BuscarRutas.setBorderPainted(false);
        
        MapaInteractivo.setOpaque(false);
        MapaInteractivo.setContentAreaFilled(false);
        MapaInteractivo.setBorderPainted(false);
        
        Pagos.setOpaque(false);
        Pagos.setContentAreaFilled(false);
        Pagos.setBorderPainted(false);
        
        Config.setOpaque(false);
        Config.setContentAreaFilled(false);
        Config.setBorderPainted(false);
        
        Cronometro.setOpaque(false);
        Cronometro.setContentAreaFilled(false);
        Cronometro.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlanearViaje = new javax.swing.JButton();
        Cronometro = new javax.swing.JButton();
        BuscarRutas = new javax.swing.JButton();
        MapaInteractivo = new javax.swing.JButton();
        Pagos = new javax.swing.JButton();
        Config = new javax.swing.JButton();
        Saldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PlanearViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PlanearViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanearViajeActionPerformed(evt);
            }
        });
        getContentPane().add(PlanearViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 160));

        Cronometro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cronometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CronometroActionPerformed(evt);
            }
        });
        getContentPane().add(Cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        BuscarRutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarRutasActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 160, 160));

        MapaInteractivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MapaInteractivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapaInteractivoActionPerformed(evt);
            }
        });
        getContentPane().add(MapaInteractivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 160, 160));

        Pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosActionPerformed(evt);
            }
        });
        getContentPane().add(Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 160, 160));

        Config.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigActionPerformed(evt);
            }
        });
        getContentPane().add(Config, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 50, 50));

        Saldo.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        Saldo.setText("SALDO AQUÍ");
        getContentPane().add(Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 130, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src_images/Main.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlanearViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanearViajeActionPerformed
        // TODO add your handling code here:
        new Travel().setVisible(true);
       dispose(); 
    }//GEN-LAST:event_PlanearViajeActionPerformed

    private void CronometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CronometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CronometroActionPerformed

    private void BuscarRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarRutasActionPerformed
        // TODO add your handling code here:
        
        new Search().setVisible(true);
        dispose();
    }//GEN-LAST:event_BuscarRutasActionPerformed

    private void MapaInteractivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapaInteractivoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MapaInteractivoActionPerformed

    private void PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosActionPerformed
        // TODO add your handling code here:
        new Payment().setVisible(true);
        dispose();
    }//GEN-LAST:event_PagosActionPerformed

    private void ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigActionPerformed
        // TODO add your handling code here:
        new Config().setVisible(true);
        dispose();
    }//GEN-LAST:event_ConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarRutas;
    private javax.swing.JButton Config;
    private javax.swing.JButton Cronometro;
    private javax.swing.JButton MapaInteractivo;
    private javax.swing.JButton Pagos;
    private javax.swing.JButton PlanearViaje;
    private javax.swing.JLabel Saldo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
