package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Rubén Darío Martínez
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaButton();
    }
    
    public void transparenciaButton(){
        Back.setOpaque(false);
        Back.setContentAreaFilled(false);
        Back.setBorderPainted(false);
        
        Recargame.setOpaque(false);
        Recargame.setContentAreaFilled(false);
        Recargame.setBorderPainted(false);
        
        PagarQR.setOpaque(false);
        PagarQR.setContentAreaFilled(false);
        PagarQR.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saldo = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        PagarQR = new javax.swing.JButton();
        ValorRecarga = new javax.swing.JTextField();
        CuentaBancaria = new javax.swing.JTextField();
        Recargame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Saldo.setFont(new java.awt.Font("Rubik", 1, 14)); // NOI18N
        Saldo.setText("SALDO AQUÍ");
        getContentPane().add(Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, 70));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        PagarQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PagarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarQRActionPerformed(evt);
            }
        });
        getContentPane().add(PagarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 210, 50));

        ValorRecarga.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        ValorRecarga.setForeground(new java.awt.Color(61, 61, 61));
        ValorRecarga.setToolTipText("User");
        ValorRecarga.setBorder(null);
        ValorRecarga.setSelectedTextColor(new java.awt.Color(87, 81, 81));
        ValorRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorRecargaActionPerformed(evt);
            }
        });
        getContentPane().add(ValorRecarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 200, 30));

        CuentaBancaria.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        CuentaBancaria.setForeground(new java.awt.Color(61, 61, 61));
        CuentaBancaria.setToolTipText("User");
        CuentaBancaria.setBorder(null);
        CuentaBancaria.setSelectedTextColor(new java.awt.Color(87, 81, 81));
        CuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaBancariaActionPerformed(evt);
            }
        });
        getContentPane().add(CuentaBancaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 200, 20));

        Recargame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Recargame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargameActionPerformed(evt);
            }
        });
        getContentPane().add(Recargame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 290, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src_images/Payment.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValorRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorRecargaActionPerformed

    private void CuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaBancariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaBancariaActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void PagarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarQRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagarQRActionPerformed

    private void RecargameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecargameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecargameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField CuentaBancaria;
    private javax.swing.JButton PagarQR;
    private javax.swing.JButton Recargame;
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField ValorRecarga;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
