package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Rubén Darío Martínez
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaButton();
    }
    
      public void transparenciaButton(){
        Back.setOpaque(false);
        Back.setContentAreaFilled(false);
        Back.setBorderPainted(false);
        
        Buscar.setOpaque(false);
        Buscar.setContentAreaFilled(false);
        Buscar.setBorderPainted(false);
        
        MasCercana.setOpaque(false);
        MasCercana.setContentAreaFilled(false);
        MasCercana.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PuntoPartida = new javax.swing.JTextField();
        PuntoPartida1 = new javax.swing.JTextField();
        MasCercana = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PuntoPartida.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        PuntoPartida.setForeground(new java.awt.Color(61, 61, 61));
        PuntoPartida.setToolTipText("User");
        PuntoPartida.setBorder(null);
        PuntoPartida.setSelectedTextColor(new java.awt.Color(87, 81, 81));
        PuntoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(PuntoPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 180, 20));

        PuntoPartida1.setFont(new java.awt.Font("Rubik", 1, 18)); // NOI18N
        PuntoPartida1.setForeground(new java.awt.Color(61, 61, 61));
        PuntoPartida1.setToolTipText("User");
        PuntoPartida1.setBorder(null);
        PuntoPartida1.setSelectedTextColor(new java.awt.Color(87, 81, 81));
        PuntoPartida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntoPartida1ActionPerformed(evt);
            }
        });
        getContentPane().add(PuntoPartida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 20));

        MasCercana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MasCercana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasCercanaActionPerformed(evt);
            }
        });
        getContentPane().add(MasCercana, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, 200, 50));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src_images/Search.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PuntoPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntoPartidaActionPerformed

    private void PuntoPartida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntoPartida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntoPartida1ActionPerformed

    private void MasCercanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasCercanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasCercanaActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton MasCercana;
    private javax.swing.JTextField PuntoPartida;
    private javax.swing.JTextField PuntoPartida1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
